repos:
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      args: [--safe]
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: flake8
      args: ['--max-line-length=88', '--select=W291,W292,W293,F401']
      language_version: python3

